# fly.toml app configuration file generated for v-yt-tt-bot on 2025-02-28T18:59:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'v-yt-tt-bot'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = 256
  cpu_kind = 'shared'
  cpus = 1
